"use client";
import { useCallback,useEffect,useRef,useState,type FormEvent,type ReactNode } from 'react';
import {Gift,Wallet,Plus,Search,SlidersHorizontal,ShieldCheck,ArrowUpRight,X,Check,Copy,LockKeyhole,ShoppingBag,LoaderCircle,ExternalLink,RefreshCw,Settings2} from 'lucide-react';
import type {Address,Hex} from 'viem';
import {sampleProducts,demoUpload,demoDelivery} from '@/lib/cardlane/demo';
import {api,connect,products,purchase,deliver,listCard,transact,resolveDispute,network,wallet,publicClient,type Product} from '@/lib/cardlane/client';
import type {AppConfig} from '@/lib/cardlane/config';import {TestUSDCAbi} from '@/lib/cardlane/TestUSDC-abi';import {hex,fresh} from '@/lib/cardlane/crypto';
const brands=['Coffee Club','Play District','Everyday Store','Frame Studio'];const categories=['全部','购物','游戏','餐饮','订阅'];const states=['不存在','待售','待验收','纠纷处理中','已完成','已退款','已下架'];
function Modal({title,close,children,busy=false}:{title:string;close:()=>void;children:ReactNode;busy?:boolean}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close();},[]);return <dialog ref={ref} className="modal" aria-label={title} onCancel={e=>{e.preventDefault();if(!busy)close();}}><div className="modal-heading"><h2>{title}</h2><button aria-label="关闭" onClick={close} disabled={busy}><X size={20}/></button></div>{children}</dialog>;}
export default function Home(){
 const [view,setView]=useState<'market'|'orders'|'selling'|'disputes'>('market');const [demo,setDemo]=useState(true);const [cards,setCards]=useState<Product[]>(sampleProducts);const [config,setConfig]=useState<AppConfig|null>(null);const [account,setAccount]=useState<Address>();const [query,setQuery]=useState('');const [category,setCategory]=useState('全部');const [region,setRegion]=useState('全部地区');const [sort,setSort]=useState('recent');const [selected,setSelected]=useState<Product|null>(null);const [sellOpen,setSellOpen]=useState(false);const [settings,setSettings]=useState(false);const [busy,setBusy]=useState('');const [error,setError]=useState('');const [secret,setSecret]=useState<{code:string;pin:string}|null>(null);const [copied,setCopied]=useState(false);const [toast,setToast]=useState('');const [tx,setTx]=useState<Hex>();const [loading,setLoading]=useState(false);const [page,setPage]=useState(0);const [total,setTotal]=useState(0);
 useEffect(()=>{api<AppConfig>('/api/config').then(setConfig).catch(()=>setError('无法读取服务状态，请刷新页面'));},[]);
 useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(id);},[toast]);
 useEffect(()=>{const p=window.ethereum;const changed=()=>{setAccount(undefined);setSecret(null);setSelected(null);setTx(undefined);};const chainChanged=()=>{setSecret(null);setSelected(null);};p?.on?.('accountsChanged',changed);p?.on?.('chainChanged',chainChanged);return()=>{p?.removeListener?.('accountsChanged',changed);p?.removeListener?.('chainChanged',chainChanged);};},[]);
 const refresh=useCallback(async()=>{if(demo)return;setLoading(true);try{const r=await products(page);setCards(r.items);setTotal(r.count);if(r.failed)setError(`${r.failed} 个商品的加密文件暂不可读，请稍后刷新`);}catch(e){setError((e as Error).message);}finally{setLoading(false);}},[demo,page]);useEffect(()=>{if(!demo&&config?.contractReady)void refresh();},[demo,config,refresh]);
 const acting=async(fn:()=>Promise<void>)=>{if(busy)return;setError('');setBusy('正在处理');try{await fn();}catch(e){setError((e as Error).message||'操作失败，请重试');}finally{setBusy('');}};
 const switchMode=()=>{setPage(0);setDemo(!demo);setCards(demo?[]:sampleProducts);setSelected(null);setSecret(null);setView('market');setError('');setTx(undefined);};
 const openCard=(p:Product)=>{setSelected(p);setSecret(null);setCopied(false);setError('');setTx(undefined);};
 const decrypt=async(p:Product)=>{setBusy(demo?'正在演示本地解密':'正在核验取卡权限');setSecret(demo?await demoDelivery(p):await deliver(config!,account!,p));};
 const buy=()=>acting(async()=>{if(!selected)return;let updated={...selected,state:2};if(demo){setBusy('正在演示付款');setCards(prev=>prev.map(p=>p.id===selected.id?updated:p));}else{if(!config?.ready)throw new Error('请先完成测试网服务接入');if(!account)throw new Error('请先连接钱包');const hash=await purchase(config,account,selected,setBusy);setTx(hash);updated={...updated,buyer:account,paidAt:Math.floor(Date.now()/1000)};setCards(prev=>prev.map(p=>p.id===updated.id?updated:p));}setSelected(updated);await decrypt(updated);});
 const changeState=(name:'confirm'|'dispute'|'cancel'|'sellerRefund'|'settleAfterWindow',state:number)=>acting(async()=>{if(!selected)return;if(!demo){if(!config?.ready||!account)throw new Error('请先连接已配置的测试网钱包');setTx(await transact(config,account,name,selected.id));}const updated={...selected,state};setCards(prev=>prev.map(p=>p.id===updated.id?updated:p));setSelected(updated);if(state===5||state===6)setSecret(null);setToast(state===4?'订单已完成':state===3?'订单已进入纠纷处理':state===5?'订单已退款':'商品已下架');});
 const submitSell=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=event.currentTarget;const data=new FormData(form);const input={brand:String(data.get('brand')),category:String(data.get('category')),region:String(data.get('region')),face:String(data.get('face')),price:String(data.get('price')),code:String(data.get('code')).trim(),pin:String(data.get('pin')).trim()};void acting(async()=>{if(!input.code||!/^\d+(\.\d{1,2})?$/.test(input.face)||!/^\d+(\.\d{1,6})?$/.test(input.price)||Number(input.price)<=0||Number(input.face)<=0||Number(input.face)>10000||Number(input.price)>Number(input.face))throw new Error('请填写有效金额；售价不能超过面额');if(demo){const p:Product={id:('0x'+hex(fresh(32))) as Hex,brand:input.brand,category:input.category,region:input.region,face:Number(input.face),price:Number(input.price),state:1,color:input.category==='餐饮'?'coffee':input.category==='游戏'?'play':input.category==='订阅'?'studio':'store',seller:'0x0000000000000000000000000000000000000001'};setBusy('正在浏览器内加密');await demoUpload(p,{code:input.code,pin:input.pin});setCards(prev=>[p,...prev]);}else{if(!config?.ready||!account)throw new Error('请先配置服务并连接有卖家资格的钱包');setTx(await listCard(config,account,input,setBusy));await refresh();}form.reset();setSellOpen(false);setToast(demo?'演示商品已上架 · 仅本次会话有效':'测试网商品已上架');});};
 const owned=(p:Product)=>demo?p.state!==1&&p.state!==6:!!account&&p.buyer?.toLowerCase()===account.toLowerCase();
 const selling=(p:Product)=>demo?!!p.seller:!!account&&p.seller?.toLowerCase()===account.toLowerCase();
 const isArbiter=!demo&&!!account&&account.toLowerCase()===config?.arbiter.toLowerCase();
 const resolve=(refundBuyer:boolean)=>acting(async()=>{if(!selected||!config||!account)throw new Error('请先连接仲裁钱包');setTx(await resolveDispute(config,account,selected.id,refundBuyer));const updated={...selected,state:refundBuyer?5:4};setCards(prev=>prev.map(p=>p.id===updated.id?updated:p));setSelected(updated);setSecret(null);setToast('争议已处理');});
 const visible=cards.filter(p=>view==='disputes'?p.state===3:view==='orders'?owned(p):view==='selling'?selling(p):p.state===1).filter(p=>(category==='全部'||p.category===category)&&(region==='全部地区'||p.region===region)&&p.brand.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='price'?a.price-b.price:sort==='discount'?(1-b.price/b.face)-(1-a.price/a.face):0);
 const needsWallet=!demo&&!account;const selectedBuyer=selected&&owned(selected);const selectedSeller=selected&&selling(selected);const canShow=selectedBuyer&&selected&&[2,3,4].includes(selected.state);
 return <div><header><a className="wordmark" href="/"><span className="logo"><Gift size={22}/></span>cardlane<span className="beta">TESTNET</span></a><nav>{[['market','礼品卡市场'],['orders','我的订单'],['selling','我出售的'],...(isArbiter?[['disputes','争议处理']]:[])].map(([key,label])=><button key={key} className={view===key?'nav-active':''} onClick={()=>{setView(key as typeof view);setCategory('全部');setQuery('');}}>{label}{key==='orders'&&cards.some(owned)&&<span className="count-badge">{cards.filter(owned).length}</span>}</button>)}</nav><button className="wallet" onClick={()=>void acting(async()=>{setAccount(await connect());setToast('钱包已连接');})} disabled={!!busy}><Wallet size={17}/>{account?account.slice(0,6)+'…'+account.slice(-4):'连接钱包'}</button></header>
 <div className="environment"><span>{demo?'演示模式 · 无真实付款 · 示例卡不可兑换 · 刷新会清空演示订单':'Base Sepolia 测试网 · 请勿使用真实礼品卡'} </span><div><button onClick={()=>setSettings(true)}><Settings2 size={13}/>接入状态</button><button onClick={switchMode} disabled={!!busy}>{demo?'切换测试网':'返回演示'}</button></div></div>
 <main><div className="page-title"><div><div className="eyebrow">{view==='market'?'THE GIFT CARD MARKET':view==='orders'?'YOUR ORDERS':view==='disputes'?'DISPUTE RESOLUTION':'YOUR LISTINGS'}</div><h1>{view==='market'?'下一张礼品卡，少花一点。':view==='orders'?'你的礼品卡，在这里。':view==='disputes'?'处理交易双方的争议。':'把闲置的卡，交给需要的人。'}</h1><p>{view==='market'?'找到合适的卡。付款后，自动获取卡密。':view==='orders'?'查看卡密、确认收货，或提交订单争议。':view==='disputes'?'核实双方材料后，决定向买家退款或向卖家放款。':'管理出售中的礼品卡与订单。'}</p></div><button className="primary" onClick={()=>{setError('');setSellOpen(true);}}><Plus size={18}/>出售礼品卡</button></div>
 {error&&!selected&&!sellOpen&&<div role="alert" className="error">{error}<button aria-label="关闭提示" onClick={()=>setError('')}><X size={16}/></button></div>}
 {!demo&&!config?.ready&&<div className="notice"><LockKeyhole size={19}/><div><strong>测试网服务尚未接通</strong><p>合约、加密存储和自动交付完成配置后，才能进行链上交易。</p></div><button onClick={()=>setSettings(true)}>查看状态</button></div>}
 <section className="market-layout"><aside><div className="aside-title"><SlidersHorizontal size={16}/>筛选商品</div><label>商品类别</label><div className="categories">{categories.map(x=><button key={x} className={category===x?'selected':''} onClick={()=>setCategory(x)}>{x}<span>{cards.filter(p=>(view==='orders'?owned(p):view==='selling'?selling(p):p.state===1)&&(x==='全部'||p.category===x)).length}</span></button>)}</div><div className="aside-note"><ShieldCheck size={22}/><strong>付款后自动取卡</strong><p>卡密加密保存，取卡权限绑定订单买家。</p><small>{demo?'演示密文只保存在当前浏览器内存中，未上传 Filecoin。':'资金先托管。收货确认或验收期结束后才向卖家放款。'}</small></div></aside><div className="market"><div className="search-row"><div className="search"><Search size={19}/><input aria-label="搜索礼品卡" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索礼品卡"/></div><select aria-label="适用地区" value={region} onChange={e=>setRegion(e.target.value)}>{['全部地区','全球','美国','加拿大'].map(r=><option key={r}>{r}</option>)}</select></div><div className="result-row"><strong>{view==='market'?(category==='全部'?'全部礼品卡':category+'礼品卡'):view==='orders'?'已购买的礼品卡':'出售记录'} <span className="result-count">{visible.length}</span></strong><div><button aria-label="刷新商品" onClick={()=>void refresh()} disabled={loading||demo}><RefreshCw size={15} className={loading?'spin':''}/></button><select aria-label="排序" value={sort} onChange={e=>setSort(e.target.value)}><option value="recent">最近上架</option><option value="discount">折扣优先</option><option value="price">价格从低到高</option></select></div></div>
 <div className="cards">{visible.map(c=><article className="product" key={c.id}><button className={'card-face '+c.color} onClick={()=>openCard(c)} aria-label={'查看 '+c.brand+' '+c.face+' 美元礼品卡'}><div className="face-top">{c.brand}<span className="brand-initial">GC</span></div><div className="face-value"><span>$</span>{c.face}<small>GIFT CARD</small></div></button><div className="product-body"><div className="product-title"><h2>{c.brand}</h2><span className="discount">{c.state===1?'省 '+Math.round((1-c.price/c.face)*100)+'%':states[c.state]}</span></div><p>{c.region} · {c.category} · 测试商户</p><div className="product-bottom"><div><strong>{c.price.toFixed(2)}</strong><span>testUSDC</span></div><button aria-label={'打开 '+c.brand+' 订单详情'} onClick={()=>openCard(c)}><ArrowUpRight size={19}/></button></div></div></article>)}</div>
 {!visible.length&&<div className="empty"><ShoppingBag size={32}/><h2>{loading?'正在读取测试网商品':view==='orders'?'还没有购买记录':view==='selling'?'还没有出售记录':'没有找到礼品卡'}</h2><p>{needsWallet?'连接钱包后查看属于你的订单。':view==='market'?'试试其他关键词或类别。':view==='orders'?'去市场挑选一张测试卡，体验付款后自动取卡。':'点击出售礼品卡，创建你的第一张测试商品。'}</p>{view==='orders'&&<button className="secondary" onClick={()=>setView('market')}>浏览礼品卡</button>}</div>}{!demo&&total>24&&<div className="pagination"><button className="secondary" disabled={page===0||loading} onClick={()=>setPage(page-1)}>上一页</button><span>第 {page+1} / {Math.ceil(total/24)} 页</span><button className="secondary" disabled={(page+1)*24>=total||loading} onClick={()=>setPage(page+1)}>下一页</button></div>}</div></section>
 <footer><span>© CardLane</span><span>加密存储 · 链上托管 · 自动交付</span><span>{demo?'交互演示':'Base Sepolia'}</span></footer></main>
 {selected&&<Modal title={selected.brand+' 礼品卡'} close={()=>{setSelected(null);setSecret(null);setError('');}} busy={!!busy}><div className={'card-face detail-face '+selected.color}><div className="face-top">{selected.brand}<span>测试商户</span></div><div className="face-value"><span>$</span>{selected.face}<small>GIFT CARD</small></div></div><div className="details"><div><span>适用地区</span><strong>{selected.region}</strong></div><div><span>售价</span><strong>{selected.price.toFixed(2)} testUSDC</strong></div><div><span>订单状态</span><strong>{states[selected.state]}</strong></div><div><span>交付方式</span><strong>付款后自动解密</strong></div></div><p className="fine-print">{demo?'当前是交互演示，不发送链上交易，也不调用 Filecoin 或 Lit。':'付款后资金进入托管，2 天内可提出争议；未提出争议时卖家可申请结算。礼品卡有效性仍需验收。'}</p>
 {error&&<div role="alert" className="error">{error}</div>}{busy&&<div className="progress" role="status"><LoaderCircle size={18} className="spin"/>{busy}</div>}
 {secret&&<section className="secret-panel"><div className="secret-heading"><Check size={17}/>卡密已解密<span>{demo?'演示卡':'测试卡'}</span></div><label>兑换码</label><code>{secret.code}</code><label>PIN</label><code>{secret.pin||'无需 PIN'}</code><button className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(secret.code);setCopied(true);}catch{setError('无法复制，请手动选中兑换码');}}}><Copy size={14}/>{copied?'已复制':'复制兑换码'}</button></section>}
 {tx&&<a className="tx-link" target="_blank" rel="noopener noreferrer" href={'https://sepolia.basescan.org/tx/'+tx}>查看链上交易<ExternalLink size={13}/></a>}
 <div className="modal-actions">{isArbiter&&selected.state===3&&<><button className="primary" disabled={!!busy} onClick={()=>resolve(true)}>裁定退款给买家</button><button className="secondary" disabled={!!busy} onClick={()=>resolve(false)}>裁定放款给卖家</button></>}{selected.state===1&&(!selectedSeller||demo)&&<button className="primary wide" onClick={buy} disabled={!!busy||(!demo&&(!config?.ready||needsWallet))}><LockKeyhole size={17}/>{demo?'演示付款并自动取卡':'付款并自动取卡'}</button>}{selected.state===1&&selectedSeller&&<button className="secondary" disabled={!!busy} onClick={()=>changeState('cancel',6)}>下架商品</button>}{canShow&&!secret&&<button className="primary wide" disabled={!!busy} onClick={()=>void acting(()=>decrypt(selected))}>获取卡密</button>}{selectedBuyer&&selected.state===2&&<><button className="primary" disabled={!!busy} onClick={()=>changeState('confirm',4)}>确认收货并放款</button><button className="secondary" disabled={!!busy} onClick={()=>changeState('dispute',3)}>卡片有问题</button></>}{selectedSeller&&[2,3].includes(selected.state)&&<button className="secondary" disabled={!!busy} onClick={()=>changeState('sellerRefund',5)}>退款给买家</button>}{selectedSeller&&selected.state===2&&selected.paidAt&&Date.now()/1000>=selected.paidAt+172800&&<button className="primary" disabled={!!busy} onClick={()=>changeState('settleAfterWindow',4)}>验收期已过，申请结算</button>}</div>{needsWallet&&selected.state===1&&<p className="fine-print">请先通过页面顶部连接钱包。</p>}</Modal>}
 {sellOpen&&<Modal title="出售测试礼品卡" close={()=>{setSellOpen(false);setError('');}} busy={!!busy}><p className="fine-print">{demo?'演示上架仅在当前会话内保存。请使用自编测试卡密。':'仅允许已授权卖家上架。请使用测试卡，切勿填写真实兑换码。'}</p><form onSubmit={submitSell} className="sell-form"><div className="form-row"><label>测试商户<select name="brand">{brands.map(b=><option key={b}>{b}</option>)}</select></label><label>类别<select name="category">{categories.slice(1).map(b=><option key={b}>{b}</option>)}</select></label></div><label>适用地区<select name="region"><option>全球</option><option>美国</option><option>加拿大</option></select></label><div className="form-row"><label>面额（USD）<input required name="face" type="number" min="0.01" max="10000" step="0.01" placeholder="50"/></label><label>售价（testUSDC）<input required name="price" type="number" min="0.000001" max="10000" step="0.000001" placeholder="42"/></label></div><label>测试卡兑换码<input required name="code" type="password" autoComplete="off" maxLength={160} placeholder="输入自编测试兑换码"/></label><label>PIN（可选）<input name="pin" type="password" autoComplete="off" maxLength={30} placeholder="如无需 PIN，可留空"/></label><div className="inline-note"><LockKeyhole size={16}/>卡密在浏览器中加密；上传内容只包含密文。</div>{error&&<div role="alert" className="error">{error}</div>}{busy&&<div role="status" className="progress"><LoaderCircle size={17} className="spin"/>{busy}</div>}<button className="primary wide" type="submit" disabled={!!busy||(!demo&&(!config?.ready||needsWallet))}>{demo?'加密并演示上架':'加密并上架'}</button></form></Modal>}
 {settings&&<Modal title="测试网接入状态" close={()=>setSettings(false)}><div className="status-list">{[['交易合约',config?.contractReady,'Base Sepolia · testUSDC 托管'],['加密文件存储',config?.storageReady,'Filecoin / Lighthouse'],['自动交付',config?.deliveryReady,'Lit · 按订单买家核验解密权限']].map(([label,ready,note])=><div key={String(label)}><span className={ready?'status-icon ready':'status-icon'}>{ready?<Check size={18}/>:<Settings2 size={18}/>}</span><div><strong>{label}</strong><p>{note}</p></div><span className="status-label">{ready?'已配置 · 待联调':'待配置'}</span></div>)}</div><p className="fine-print">配置状态不代表外部服务已通过联调。只有完整流程验证成功后，才可开放真实交易。</p>{config?.contractReady&&<a className="tx-link" href={'https://sepolia.basescan.org/address/'+config.contract} target="_blank" rel="noopener noreferrer">查看测试网合约<ExternalLink size={13}/></a>}<button className="primary wide" disabled={demo||!config?.contractReady||!account||!!busy} onClick={()=>void acting(async()=>{await network();const hash=await wallet().writeContract({account:account!,address:config!.token as Address,abi:TestUSDCAbi,functionName:'faucet'});if((await publicClient(config!).waitForTransactionReceipt({hash})).status!=='success')throw new Error('领取失败');setToast('已领取 1000 testUSDC');})}>领取无价值测试代币</button><p className="fine-print">领取测试代币需要连接钱包并持有少量 Base Sepolia 测试 ETH。</p></Modal>}
 {toast&&<div className="toast" role="status"><Check size={17}/>{toast}</div>}
 </div>;
}
