"use client";
import { useCallback,useEffect,useRef,useState,type FormEvent,type ReactNode } from 'react';
import {Gift,Globe,Wallet,Plus,Search,SlidersHorizontal,ShieldCheck,ArrowUpRight,X,Check,Copy,LockKeyhole,ShoppingBag,LoaderCircle,ExternalLink,RefreshCw,Settings2} from 'lucide-react';
import type {Address,Hex} from 'viem';
import {sampleProducts,demoUpload,demoDelivery} from '@/lib/cardlane/demo';
import {api,connect,products,purchase,deliver,listCard,transact,resolveDispute,network,wallet,publicClient,type Product} from '@/lib/cardlane/client';
import type {AppConfig} from '@/lib/cardlane/config';import {TestUSDCAbi} from '@/lib/cardlane/TestUSDC-abi';import {hex,fresh} from '@/lib/cardlane/crypto';
import {LanguageProvider,useLanguage} from '@/lib/cardlane/language';
const brands=['Coffee Club','Play District','Everyday Store','Frame Studio'];const categories=['全部','购物','游戏','餐饮','订阅'];const states=['不存在','待售','待验收','纠纷处理中','已完成','已退款','已下架'];
function Modal({title,close,children,busy=false}:{title:string;close:()=>void;children:ReactNode;busy?:boolean}){const {t}=useLanguage();const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close();},[]);return <dialog ref={ref} className="modal" aria-label={title} onCancel={e=>{e.preventDefault();if(!busy)close();}}><div className="modal-heading"><h2>{title}</h2><button aria-label={t("关闭")} onClick={close} disabled={busy}><X size={20}/></button></div>{children}</dialog>;}
export default function Home(){return <LanguageProvider><CardLane/></LanguageProvider>;}
function CardLane(){
 const {language,setLanguage,t}=useLanguage();
 const [view,setView]=useState<'market'|'orders'|'selling'|'disputes'>('market');const [demo,setDemo]=useState(true);const [cards,setCards]=useState<Product[]>(sampleProducts);const [config,setConfig]=useState<AppConfig|null>(null);const [account,setAccount]=useState<Address>();const [query,setQuery]=useState('');const [category,setCategory]=useState('全部');const [region,setRegion]=useState('全部地区');const [sort,setSort]=useState('recent');const [selected,setSelected]=useState<Product|null>(null);const [sellOpen,setSellOpen]=useState(false);const [settings,setSettings]=useState(false);const [busy,setBusy]=useState('');const [error,setError]=useState('');const [secret,setSecret]=useState<{code:string;pin:string}|null>(null);const [copied,setCopied]=useState(false);const [toast,setToast]=useState('');const [tx,setTx]=useState<Hex>();const [loading,setLoading]=useState(false);const [page,setPage]=useState(0);const [total,setTotal]=useState(0);
 useEffect(()=>{api<AppConfig>('/api/config').then(setConfig).catch(()=>setError('无法读取服务状态，请刷新页面'));},[]);
 useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(id);},[toast]);
 useEffect(()=>{const p=window.ethereum;const changed=()=>{setAccount(undefined);setSecret(null);setSelected(null);setTx(undefined);};const chainChanged=()=>{setSecret(null);setSelected(null);};p?.on?.('accountsChanged',changed);p?.on?.('chainChanged',chainChanged);return()=>{p?.removeListener?.('accountsChanged',changed);p?.removeListener?.('chainChanged',chainChanged);};},[]);
 const refresh=useCallback(async()=>{if(demo)return;setLoading(true);try{const r=await products(page);setCards(r.items);setTotal(r.count);if(r.failed)setError(`${r.failed} 个商品的加密文件暂不可读，请稍后刷新`);}catch(e){setError((e as Error).message);}finally{setLoading(false);}},[demo,page]);useEffect(()=>{if(!demo&&config?.contractReady)void refresh();},[demo,config,refresh]);
 const acting=async(fn:()=>Promise<void>)=>{if(busy)return;setError('');setBusy('正在处理');try{await fn();}catch(e){setError((e as Error).message||'操作失败，请重试');}finally{setBusy('');}};
 const switchMode=()=>{setPage(0);setDemo(!demo);setCards(demo?[]:sampleProducts);setSelected(null);setSecret(null);setView('market');setError('');setTx(undefined);};
 const openCard=(p:Product)=>{setSelected(p);setSecret(null);setCopied(false);setError('');setTx(undefined);};
 const decrypt=async(p:Product)=>{setBusy(demo?'正在演示本地解密':'正在核验取卡权限');setSecret(demo?await demoDelivery(p):await deliver(config!,account!,p));};
 const buy=()=>acting(async()=>{if(!selected)return;let updated={...selected,state:2};if(demo){setBusy('正在演示付款');setCards(prev=>prev.map(p=>p.id===selected.id?updated:p));}else{if(!config?.ready)throw new Error('请先完成测试网服务接入');if(!account)throw new Error('请先连接钱包');const hash=await purchase(config,account,selected,setBusy);setTx(hash);updated={...updated,buyer:account,paidAt:Math.floor(Date.now()/1000)};setCards(prev=>prev.map(p=>p.id===updated.id?updated:p));}setSelected(updated);await decrypt(updated);});
 const changeState=(name:'confirm'|'dispute'|'cancel'|'sellerRefund'|'settleAfterWindow',state:number)=>acting(async()=>{if(!selected)return;if(!demo){if(!config?.ready||!account)throw new Error('请先连接已配置的测试网钱包');setTx(await transact(config,account,name,selected.id));}const updated={...selected,state};setCards(prev=>prev.map(p=>p.id===updated.id?updated:p));setSelected(updated);if(state===5||state===6)setSecret(null);setToast(state===4?'订单已完成':state===3?'订单已进入纠纷处理':state===5?'订单已退款':'商品已下架');});
 const submitSell=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=event.currentTarget;const data=new FormData(form);const input={brand:String(data.get('brand')),category:String(data.get('category')),region:String(data.get('region')),face:String(data.get('face')),price:String(data.get('price')),code:String(data.get('code')).trim(),pin:String(data.get('pin')).trim()};void acting(async()=>{if(!input.code||!/^\d+(\.\d{1,2})?$/.test(input.face)||!/^\d+(\.\d{1,6})?$/.test(input.price)||Number(input.price)<=0||Number(input.face)<=0||Number(input.face)>10000||Number(input.price)>Number(input.face))throw new Error('请填写有效金额；售价不能超过面额');if(demo){const p:Product={id:('0x'+hex(fresh(32))) as Hex,brand:input.brand,category:input.category,region:input.region,face:Number(input.face),price:Number(input.price),state:1,color:input.category==='餐饮'?'coffee':input.category==='游戏'?'play':input.category==='订阅'?'studio':'store',seller:'0x0000000000000000000000000000000000000001'};setBusy('正在浏览器内加密');await demoUpload(p,{code:input.code,pin:input.pin});setCards(prev=>[p,...prev]);}else{if(!config?.ready||!account)throw new Error('请先配置服务并连接有卖家资格的钱包');setTx(await listCard(config,account,input,setBusy));await refresh();}form.reset();setSellOpen(false);setToast(demo?'演示商品已上架 · 仅本次会话有效':'测试网商品已上架');});};
 const owned=(p:Product)=>demo?p.state!==1&&p.state!==6:!!account&&p.buyer?.toLowerCase()===account.toLowerCase();
 const selling=(p:Product)=>demo?!!p.seller:!!account&&p.seller?.toLowerCase()===account.toLowerCase();
 const isArbiter=!demo&&!!account&&account.toLowerCase()===config?.arbiter.toLowerCase();
 const resolve=(refundBuyer:boolean)=>acting(async()=>{if(!selected||!config||!account)throw new Error('请先连接仲裁钱包');setTx(await resolveDispute(config,account,selected.id,refundBuyer));const updated={...selected,state:refundBuyer?5:4};setCards(prev=>prev.map(p=>p.id===updated.id?updated:p));setSelected(updated);setSecret(null);setToast('争议已处理');});
 const visible=cards.filter(p=>view==='disputes'?p.state===3:view==='orders'?owned(p):view==='selling'?selling(p):p.state===1).filter(p=>(category==='全部'||p.category===category)&&(region==='全部地区'||p.region===region)&&p.brand.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='price'?a.price-b.price:sort==='discount'?(1-b.price/b.face)-(1-a.price/a.face):0);
 const needsWallet=!demo&&!account;const selectedBuyer=selected&&owned(selected);const selectedSeller=selected&&selling(selected);const canShow=selectedBuyer&&selected&&[2,3,4].includes(selected.state);
 return <div><header><a className="wordmark" href="/"><span className="logo"><Gift size={22}/></span>cardlane<span className="beta">TESTNET</span></a><nav>{[['market',t("礼品卡市场")],['orders',t("我的订单")],['selling',t("我出售的")],...(isArbiter?[['disputes',t("争议处理")]]:[])].map(([key,label])=><button key={key} className={view===key?'nav-active':''} onClick={()=>{setView(key as typeof view);setCategory('全部');setQuery('');}}>{t(label)}{key==='orders'&&cards.some(owned)&&<span className="count-badge">{cards.filter(owned).length}</span>}</button>)}</nav><div className="language-switch" title={language==='en'?'Choose language':'选择语言'}><Globe size={19} aria-hidden="true"/><select aria-label="Language / 语言" value={language} onChange={e=>setLanguage(e.target.value as 'zh'|'en')}><option value="zh">中文</option><option value="en">English</option></select></div><button className="wallet" onClick={()=>void acting(async()=>{setAccount(await connect());setToast("钱包已连接");})} disabled={!!busy}><Wallet size={17}/>{account?account.slice(0,6)+'…'+account.slice(-4):t("连接钱包")}</button></header>
 <div className="environment"><span>{demo?t("演示模式 · 无真实付款 · 示例卡不可兑换 · 刷新会清空演示订单"):t("Base Sepolia 测试网 · 请勿使用真实礼品卡")} </span><div><button onClick={()=>setSettings(true)}><Settings2 size={13}/>{t("接入状态")}</button><button onClick={switchMode} disabled={!!busy}>{demo?t("切换测试网"):t("返回演示")}</button></div></div>
 <main><div className="page-title"><div><div className="eyebrow">{view==='market'?'THE GIFT CARD MARKET':view==='orders'?'YOUR ORDERS':view==='disputes'?'DISPUTE RESOLUTION':'YOUR LISTINGS'}</div><h1>{view==='market'?t("下一张礼品卡，少花一点。"):view==='orders'?t("你的礼品卡，在这里。"):view==='disputes'?t("处理交易双方的争议。"):t("把闲置的卡，交给需要的人。")}</h1><p>{view==='market'?t("找到合适的卡。付款后，自动获取卡密。"):view==='orders'?t("查看卡密、确认收货，或提交订单争议。"):view==='disputes'?t("核实双方材料后，决定向买家退款或向卖家放款。"):t("管理出售中的礼品卡与订单。")}</p></div><button className="primary" onClick={()=>{setError('');setSellOpen(true);}}><Plus size={18}/>{t("出售礼品卡")}</button></div>
 {error&&!selected&&!sellOpen&&<div role="alert" className="error">{t(String(error))}<button aria-label={t("关闭提示")} onClick={()=>setError('')}><X size={16}/></button></div>}
 {!demo&&!config?.ready&&<div className="notice"><LockKeyhole size={19}/><div><strong>{t("测试网服务尚未接通")}</strong><p>{t("合约、加密存储和自动交付完成配置后，才能进行链上交易。")}</p></div><button onClick={()=>setSettings(true)}>{t("查看状态")}</button></div>}
 <section className="market-layout"><aside><div className="aside-title"><SlidersHorizontal size={16}/>{t("筛选商品")}</div><label>{t("商品类别")}</label><div className="categories">{categories.map(x=><button key={x} className={category===x?'selected':''} onClick={()=>setCategory(x)}>{t(x)}<span>{cards.filter(p=>(view==='orders'?owned(p):view==='selling'?selling(p):p.state===1)&&(x==='全部'||p.category===x)).length}</span></button>)}</div><div className="aside-note"><ShieldCheck size={22}/><strong>{t("付款后自动取卡")}</strong><p>{t("卡密加密保存，取卡权限绑定订单买家。")}</p><small>{demo?t("演示密文只保存在当前浏览器内存中，未上传 Filecoin。"):t("资金先托管。收货确认或验收期结束后才向卖家放款。")}</small></div></aside><div className="market"><div className="search-row"><div className="search"><Search size={19}/><input aria-label={t("搜索礼品卡")} value={query} onChange={e=>setQuery(e.target.value)} placeholder={t("搜索礼品卡")}/></div><select aria-label={t("适用地区")} value={region} onChange={e=>setRegion(e.target.value)}>{['全部地区','全球','美国','加拿大'].map(r=><option key={r} value={r}>{t(r)}</option>)}</select></div><div className="result-row"><strong>{view==='market'?(category==='全部'?t("全部礼品卡"):t(category)+(language==='en'?' gift cards':'礼品卡')):view==='orders'?t("已购买的礼品卡"):t("出售记录")} <span className="result-count">{visible.length}</span></strong><div><button aria-label={t("刷新商品")} onClick={()=>void refresh()} disabled={loading||demo}><RefreshCw size={15} className={loading?'spin':''}/></button><select aria-label={t("排序")} value={sort} onChange={e=>setSort(e.target.value)}><option value="recent">{t("最近上架")}</option><option value="discount">{t("折扣优先")}</option><option value="price">{t("价格从低到高")}</option></select></div></div>
 <div className="cards">{visible.map(c=><article className="product" key={c.id}><button className={'card-face '+c.color} onClick={()=>openCard(c)} aria-label={language==='en'?`View ${c.brand} $${c.face} gift card`:`查看 ${c.brand} ${c.face} 美元礼品卡`}><div className="face-top">{c.brand}<span className="brand-initial">GC</span></div><div className="face-value"><span>$</span>{c.face}<small>GIFT CARD</small></div></button><div className="product-body"><div className="product-title"><h2>{c.brand}</h2><span className="discount">{c.state===1?(language==='en'?'Save ':t("省 "))+Math.round((1-c.price/c.face)*100)+'%':t(states[c.state])}</span></div><p>{t(c.region)} · {t(c.category)} · {t("测试商户")}</p><div className="product-bottom"><div><strong>{c.price.toFixed(2)}</strong><span>testUSDC</span></div><button aria-label={language==='en'?`Open ${c.brand} order details`:`打开 ${c.brand} 订单详情`} onClick={()=>openCard(c)}><ArrowUpRight size={19}/></button></div></div></article>)}</div>
 {!visible.length&&<div className="empty"><ShoppingBag size={32}/><h2>{loading?t("正在读取测试网商品"):view==='orders'?t("还没有购买记录"):view==='selling'?t("还没有出售记录"):t("没有找到礼品卡")}</h2><p>{needsWallet?t("连接钱包后查看属于你的订单。"):view==='market'?t("试试其他关键词或类别。"):view==='orders'?t("去市场挑选一张测试卡，体验付款后自动取卡。"):t("点击出售礼品卡，创建你的第一张测试商品。")}</p>{view==='orders'&&<button className="secondary" onClick={()=>setView('market')}>{t("浏览礼品卡")}</button>}</div>}{!demo&&total>24&&<div className="pagination"><button className="secondary" disabled={page===0||loading} onClick={()=>setPage(page-1)}>{t("上一页")}</button><span>{language==='en'?'Page':'第'} {page+1} / {Math.ceil(total/24)} {language==='en'?'':'页'}</span><button className="secondary" disabled={(page+1)*24>=total||loading} onClick={()=>setPage(page+1)}>{t("下一页")}</button></div>}</div></section>
 <footer><span>© CardLane</span><span>{t("加密存储 · 链上托管 · 自动交付")}</span><span>{demo?t("交互演示"):'Base Sepolia'}</span></footer></main>
 {selected&&<Modal title={selected.brand+t(" 礼品卡")} close={()=>{setSelected(null);setSecret(null);setError('');}} busy={!!busy}><div className={'card-face detail-face '+selected.color}><div className="face-top">{selected.brand}<span>{t("测试商户")}</span></div><div className="face-value"><span>$</span>{selected.face}<small>GIFT CARD</small></div></div><div className="details"><div><span>{t("适用地区")}</span><strong>{t(selected.region)}</strong></div><div><span>{t("售价")}</span><strong>{selected.price.toFixed(2)} testUSDC</strong></div><div><span>{t("订单状态")}</span><strong>{t(states[selected.state])}</strong></div><div><span>{t("交付方式")}</span><strong>{t("付款后自动解密")}</strong></div></div><p className="fine-print">{demo?t("当前是交互演示，不发送链上交易，也不调用 Filecoin 或 Lit。"):t("付款后资金进入托管，2 天内可提出争议；未提出争议时卖家可申请结算。礼品卡有效性仍需验收。")}</p>
 {error&&<div role="alert" className="error">{t(String(error))}</div>}{busy&&<div className="progress" role="status"><LoaderCircle size={18} className="spin"/>{t(String(busy))}</div>}
 {secret&&<section className="secret-panel"><div className="secret-heading"><Check size={17}/>{t("卡密已解密")}<span>{demo?t("演示卡"):t("测试卡")}</span></div><label>{t("兑换码")}</label><code>{secret.code}</code><label>PIN</label><code>{secret.pin||t("无需 PIN")}</code><button className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(secret.code);setCopied(true);}catch{setError("无法复制，请手动选中兑换码");}}}><Copy size={14}/>{copied?t("已复制"):t("复制兑换码")}</button></section>}
 {tx&&<a className="tx-link" target="_blank" rel="noopener noreferrer" href={'https://sepolia.basescan.org/tx/'+tx}>{t("查看链上交易")}<ExternalLink size={13}/></a>}
 <div className="modal-actions">{isArbiter&&selected.state===3&&<><button className="primary" disabled={!!busy} onClick={()=>resolve(true)}>{t("裁定退款给买家")}</button><button className="secondary" disabled={!!busy} onClick={()=>resolve(false)}>{t("裁定放款给卖家")}</button></>}{selected.state===1&&(!selectedSeller||demo)&&<button className="primary wide" onClick={buy} disabled={!!busy||(!demo&&(!config?.ready||needsWallet))}><LockKeyhole size={17}/>{demo?t("演示付款并自动取卡"):t("付款并自动取卡")}</button>}{selected.state===1&&selectedSeller&&<button className="secondary" disabled={!!busy} onClick={()=>changeState('cancel',6)}>{t("下架商品")}</button>}{canShow&&!secret&&<button className="primary wide" disabled={!!busy} onClick={()=>void acting(()=>decrypt(selected))}>{t("获取卡密")}</button>}{selectedBuyer&&selected.state===2&&<><button className="primary" disabled={!!busy} onClick={()=>changeState('confirm',4)}>{t("确认收货并放款")}</button><button className="secondary" disabled={!!busy} onClick={()=>changeState('dispute',3)}>{t("卡片有问题")}</button></>}{selectedSeller&&[2,3].includes(selected.state)&&<button className="secondary" disabled={!!busy} onClick={()=>changeState('sellerRefund',5)}>{t("退款给买家")}</button>}{selectedSeller&&selected.state===2&&selected.paidAt&&Date.now()/1000>=selected.paidAt+172800&&<button className="primary" disabled={!!busy} onClick={()=>changeState('settleAfterWindow',4)}>{t("验收期已过，申请结算")}</button>}</div>{needsWallet&&selected.state===1&&<p className="fine-print">{t("请先通过页面顶部连接钱包。")}</p>}</Modal>}
 {sellOpen&&<Modal title={t("出售测试礼品卡")} close={()=>{setSellOpen(false);setError('');}} busy={!!busy}><p className="fine-print">{demo?t("演示上架仅在当前会话内保存。请使用自编测试卡密。"):t("仅允许已授权卖家上架。请使用测试卡，切勿填写真实兑换码。")}</p><form onSubmit={submitSell} className="sell-form"><div className="form-row"><label>{t("测试商户")}<select name="brand">{brands.map(b=><option key={b} value={b}>{t(b)}</option>)}</select></label><label>{t("类别")}<select name="category">{categories.slice(1).map(b=><option key={b} value={b}>{t(b)}</option>)}</select></label></div><label>{t("适用地区")}<select name="region">{['全球','美国','加拿大'].map(r=><option key={r} value={r}>{t(r)}</option>)}</select></label><div className="form-row"><label>{t("面额（USD）")}<input required name="face" type="number" min="0.01" max="10000" step="0.01" placeholder="50"/></label><label>{t("售价（testUSDC）")}<input required name="price" type="number" min="0.000001" max="10000" step="0.000001" placeholder="42"/></label></div><label>{t("测试卡兑换码")}<input required name="code" type="password" autoComplete="off" maxLength={160} placeholder={t("输入自编测试兑换码")}/></label><label>{t("PIN（可选）")}<input name="pin" type="password" autoComplete="off" maxLength={30} placeholder={t("如无需 PIN，可留空")}/></label><div className="inline-note"><LockKeyhole size={16}/>{t("卡密在浏览器中加密；上传内容只包含密文。")}</div>{error&&<div role="alert" className="error">{t(String(error))}</div>}{busy&&<div role="status" className="progress"><LoaderCircle size={17} className="spin"/>{t(String(busy))}</div>}<button className="primary wide" type="submit" disabled={!!busy||(!demo&&(!config?.ready||needsWallet))}>{demo?t("加密并演示上架"):t("加密并上架")}</button></form></Modal>}
 {settings&&<Modal title={t("测试网接入状态")} close={()=>setSettings(false)}><div className="status-list">{[[t("交易合约"),config?.contractReady,t("Base Sepolia · testUSDC 托管")],[t("加密文件存储"),config?.storageReady,'Filecoin / Lighthouse'],[t("自动交付"),config?.deliveryReady,t("Lit · 按订单买家核验解密权限")]].map(([label,ready,note])=><div key={String(label)}><span className={ready?'status-icon ready':'status-icon'}>{ready?<Check size={18}/>:<Settings2 size={18}/>}</span><div><strong>{t(String(label))}</strong><p>{t(String(note))}</p></div><span className="status-label">{ready?t("已配置 · 待联调"):t("待配置")}</span></div>)}</div><p className="fine-print">{t("配置状态不代表外部服务已通过联调。只有完整流程验证成功后，才可开放真实交易。")}</p>{config?.contractReady&&<a className="tx-link" href={'https://sepolia.basescan.org/address/'+config.contract} target="_blank" rel="noopener noreferrer">{t("查看测试网合约")}<ExternalLink size={13}/></a>}<button className="primary wide" disabled={demo||!config?.contractReady||!account||!!busy} onClick={()=>void acting(async()=>{await network();const hash=await wallet().writeContract({account:account!,address:config!.token as Address,abi:TestUSDCAbi,functionName:'faucet'});if((await publicClient(config!).waitForTransactionReceipt({hash})).status!=='success')throw new Error("领取失败");setToast("已领取 1000 testUSDC");})}>{t("领取无价值测试代币")}</button><p className="fine-print">{t("领取测试代币需要连接钱包并持有少量 Base Sepolia 测试 ETH。")}</p></Modal>}
 {toast&&<div className="toast" role="status"><Check size={17}/>{t(String(toast))}</div>}
 </div>;
}
