import {fileURLToPath} from 'node:url';import http from 'node:http';import fs from 'node:fs/promises';import {build} from 'esbuild';
import {createPublicClient,http as rpc,isAddress,encodeDeployData} from 'viem';import {baseSepolia} from 'viem/chains';
const client=createPublicClient({chain:baseSepolia,transport:rpc('https://sepolia.base.org')});
const root=new URL('../',import.meta.url);const output=new URL('.sites-runtime/browser-deploy/',root);await fs.mkdir(output,{recursive:true});
await build({entryPoints:[fileURLToPath(new URL('scripts/deploy-browser-client.mjs',root))],outfile:fileURLToPath(new URL('client.js',output)),bundle:true,format:'esm',platform:'browser',target:'es2022'});
const tokenArtifact=JSON.parse(await fs.readFile(new URL('generated/TestUSDC.json',root)));const escrowArtifact=JSON.parse(await fs.readFile(new URL('generated/CardLane.json',root)));
const recordFile=new URL('deployment.json',output);let saved={};try{saved=JSON.parse(await fs.readFile(recordFile));}catch{}
const page=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>CardLane · 测试网部署</title><style>*{box-sizing:border-box}body{margin:0;background:#f6f8fc;color:#172033;font:16px/1.7 system-ui,sans-serif}main{max-width:760px;margin:50px auto;padding:30px;background:white;border:1px solid #e5e9f1;border-radius:16px}h1{font-size:28px}button{font:inherit;padding:11px 18px;border:0;border-radius:8px;background:#2556ed;color:white;cursor:pointer}button:disabled{opacity:.45;cursor:not-allowed}.step{padding:22px 0;border-top:1px solid #e5e9f1}p,a{overflow-wrap:anywhere}small{color:#687386}a{color:#2556ed}.info{padding:16px;border-radius:8px;background:#eaf0ff}#message{white-space:pre-wrap} @media(max-width:700px){main{margin:16px;padding:22px}}</style><main><small>BASE SEPOLIA · CHAIN ID 84532</small><h1>部署 CardLane 测试网合约</h1><p>本页仅部署无价值 testUSDC 与礼品卡托管合约。两笔交易由你在钱包中确认，私钥始终留在钱包里。</p><div class="info"><strong>仲裁者与初始卖家：连接的钱包</strong><p id="account">未连接</p><p>余额：<span id="balance">连接后读取</span></p><button id="connect">连接浏览器钱包</button></div><section class="step"><h2>1. 部署 testUSDC</h2><p>只用于测试的支付代币，无真实价值。</p><button id="token" disabled>部署测试代币</button><p><a id="token-address">待部署</a></p></section><section class="step"><h2>2. 部署礼品卡托管</h2><p>付款托管，买家确认放款；无申诉订单 48 小时到期可结算；卖家需在申诉后 24 小时内回复。</p><button id="escrow" disabled>部署托管合约</button><p><a id="contract-address">待部署</a></p></section><button id="retry" hidden>检查已发送交易</button><p id="message" role="status">请在安装钱包扩展的浏览器打开本地页面。</p><p><a href="https://docs.base.org/get-started/get-funds" target="_blank" rel="noopener noreferrer">Base 官方测试网水龙头说明</a></p><small>合约部署成功后，自动交付和定时结算仍需接入 Lighthouse、Lit 及独立 keeper。</small></main><script type="module" src="/client.js"></script></html>`;
const json=(res,data,status=200)=>{res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(data));};
const server=http.createServer(async(req,res)=>{try{if(req.headers.host!=='127.0.0.1:5175'&&req.headers.host!=='localhost:5175'){json(res,{error:'Invalid host'},403);return;}const path=new URL(req.url,'http://127.0.0.1:5175').pathname;
if(req.method==='GET'&&path==='/'){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(page);return;}
if(req.method==='GET'&&path==='/client.js'){res.writeHead(200,{'Content-Type':'text/javascript','Cache-Control':'no-store'});res.end(await fs.readFile(new URL('client.js',output)));return;}
if(req.method==='GET'&&path==='/api/state'){json(res,saved);return;}
if(req.method==='POST'&&path==='/api/record'){if(!['http://127.0.0.1:5175','http://localhost:5175'].includes(req.headers.origin)){json(res,{error:'Invalid origin'},403);return;}let text='';for await(const chunk of req){text+=chunk;if(text.length>2000)throw new Error('Request too large');}const {name,hash}=JSON.parse(text);if(!['TestUSDC','CardLane'].includes(name)||!/^0x[0-9a-fA-F]{64}$/.test(hash))throw new Error('Invalid deployment record');if(await client.getChainId()!==84532)throw new Error('Wrong RPC chain');const [tx,receipt]=await Promise.all([client.getTransaction({hash}),client.getTransactionReceipt({hash})]);if(receipt.status!=='success'||!receipt.contractAddress||tx.to!==null)throw new Error('Not a successful contract creation');const artifact=name==='TestUSDC'?tokenArtifact:escrowArtifact;if(name==='CardLane'&&!isAddress(saved.token??''))throw new Error('Deploy token first');const args=name==='TestUSDC'?[]:[saved.token,tx.from];if(tx.input!==encodeDeployData({...artifact,args}))throw new Error('Deployment bytecode or constructor does not match');if(name==='CardLane'){const [version,token,arbiter]=await Promise.all(['VERSION','token','arbiter'].map(functionName=>client.readContract({address:receipt.contractAddress,abi:escrowArtifact.abi,functionName})));if(version!==2n||token.toLowerCase()!==saved.token.toLowerCase()||arbiter.toLowerCase()!==tx.from.toLowerCase())throw new Error('Contract verification failed');}
const key=name==='TestUSDC'?'token':'contract';if(saved[key]&&saved[key].toLowerCase()!==receipt.contractAddress.toLowerCase())throw new Error('A different deployment is already recorded');saved={...saved,[key]:receipt.contractAddress,[key+'Tx']:hash,arbiter:name==='CardLane'?tx.from:saved.arbiter,chainId:84532};await fs.writeFile(recordFile,JSON.stringify(saved,null,2)+'\n');json(res,saved);return;}
json(res,{error:'Not found'},404);
}catch(e){json(res,{error:e.message},400);}});
server.listen(5175,'127.0.0.1',()=>console.log('CardLane browser deployment: http://127.0.0.1:5175/\nNo private key is requested or stored. Waiting for user wallet confirmations.'));
