import { createPublicClient,createWalletClient,custom,http,parseUnits,formatUnits,keccak256,toHex,verifyMessage,type Address,type Hex,type EIP1193Provider } from 'viem';
import {baseSepolia} from 'viem/chains';import {CardLaneAbi} from './CardLane-abi';import {TestUSDCAbi} from './TestUSDC-abi';import {encryptCard,decryptCard,keyPair,open,hex,fresh,unhex,deliveryMessage,type Envelope} from './crypto';import type {AppConfig} from './config';
export type Product={id:Hex;brand:string;category:string;region:string;face:number;price:number;color:string;state:number;seller?:Address;buyer?:Address;cid?:string;payloadHash?:Hex;paidAt?:number;priceRaw?:string;appeal?:{openedAt:number;repliedAt:number;reason:number;reply:string}};
export type Provider=EIP1193Provider&{on?:(event:string,fn:(args:unknown)=>void)=>void;removeListener?:(event:string,fn:(args:unknown)=>void)=>void};
declare global{interface Window{ethereum?:Provider}}
export function provider(){if(!window.ethereum)throw new Error('请先安装支持 EVM 的浏览器钱包');return window.ethereum;}
export function wallet(){return createWalletClient({chain:baseSepolia,transport:custom(provider())});}
export function publicClient(c:AppConfig){return createPublicClient({chain:baseSepolia,transport:http(c.rpc,{timeout:15000})});}
export async function connect(){const accounts=await provider().request({method:'eth_requestAccounts'}) as Address[];if(!accounts[0])throw new Error('未取得钱包地址');return accounts[0];}
export async function network(){const id=await provider().request({method:'eth_chainId'});if(id!=='0x14a34'){try{await provider().request({method:'wallet_switchEthereumChain',params:[{chainId:'0x14a34'}]});}catch(e){if((e as {code?:number}).code!==4902)throw e;await provider().request({method:'wallet_addEthereumChain',params:[{chainId:'0x14a34',chainName:'Base Sepolia',nativeCurrency:{name:'Ether',symbol:'ETH',decimals:18},rpcUrls:['https://sepolia.base.org'],blockExplorerUrls:['https://sepolia.basescan.org']}]});}}if(await provider().request({method:'eth_chainId'})!=='0x14a34')throw new Error('请切换至 Base Sepolia');}
export async function api<T>(url:string,body?:unknown):Promise<T>{const response=await fetch(url,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error??'请求失败');return data as T;}
export async function envelopeFor(p:Product){if(!p.cid||!/^(Qm[1-9A-HJ-NP-Za-km-z]{44}|bafy[a-z2-7]{20,})$/.test(p.cid))throw new Error('文件标识不合法');const r=await fetch('https://gateway.lighthouse.storage/ipfs/'+p.cid,{signal:AbortSignal.timeout(20000)});if(!r.ok)throw new Error('加密文件暂不可读取');const raw=await r.text();if(raw.length>32000||keccak256(toHex(raw))!==p.payloadHash)throw new Error('加密文件与链上记录不一致');const envelope=JSON.parse(raw) as Envelope;if(envelope.version!==1||envelope.listingId!==p.id)throw new Error('文件格式不匹配');return {raw,envelope};}
export async function products(page=0){const data=await api<{count:string;listings:{id:Hex;seller:Address;buyer:Address;price:string;state:number;paidAt:string;cid:string;payloadHash:Hex;appeal:{openedAt:string;repliedAt:string;reason:number;reply:string}}[]}>('/api/listings?page='+page);const results=await Promise.allSettled(data.listings.map(async l=>{const p:Product={...l,brand:'无法读取商品信息',category:'购物',region:'未知',face:0,price:Number(formatUnits(BigInt(l.price),6)),priceRaw:l.price,appeal:{...l.appeal,openedAt:Number(l.appeal.openedAt),repliedAt:Number(l.appeal.repliedAt)},color:'store',paidAt:Number(l.paidAt)};const {envelope}=await envelopeFor(p);const m=envelope.metadata;if(!m||typeof m.brand!=='string'||m.brand.length>60||!['购物','游戏','餐饮','订阅'].includes(m.category)||!['全球','美国','加拿大'].includes(m.region)||!/^\d+(\.\d{1,2})?$/.test(m.face)||Number(m.face)<=0||Number(m.face)>10000)throw new Error('商品信息不合法');return {...p,brand:m.brand,category:m.category,region:m.region,face:Number(m.face),color:m.category==='餐饮'?'coffee':m.category==='游戏'?'play':m.category==='订阅'?'studio':'store'};}));return {count:Number(data.count),items:results.flatMap(r=>r.status==='fulfilled'?[r.value]:[]),failed:results.filter(r=>r.status==='rejected').length};}
export async function transact(c:AppConfig,account:Address,name:'confirm'|'cancel'|'sellerRefund'|'settleAfterWindow',id:Hex){await network();const hash=await wallet().writeContract({address:c.contract as Address,abi:CardLaneAbi,functionName:name,args:[id],account});const receipt=await publicClient(c).waitForTransactionReceipt({hash});if(receipt.status!=='success')throw new Error('交易未成功');return hash;}
export async function purchase(c:AppConfig,account:Address,p:Product,progress:(s:string)=>void){await network();const client=publicClient(c);const value=p.priceRaw?BigInt(p.priceRaw):parseUnits(p.price.toFixed(6),6);progress('正在授权测试代币');const approval=await wallet().writeContract({account,address:c.token as Address,abi:TestUSDCAbi,functionName:'approve',args:[c.contract as Address,value]});if((await client.waitForTransactionReceipt({hash:approval})).status!=='success')throw new Error('代币授权失败');progress('正在确认付款');const hash=await wallet().writeContract({account,address:c.contract as Address,abi:CardLaneAbi,functionName:'buy',args:[p.id,value,p.payloadHash! ]});if((await client.waitForTransactionReceipt({hash})).status!=='success')throw new Error('付款失败');return hash;}
export async function deliver(c:AppConfig,account:Address,p:Product){const {raw,envelope}=await envelopeFor(p);const pair=keyPair();const expires=Math.floor(Date.now()/1000)+180;const recipient=hex(pair.publicKey);const message=deliveryMessage(c.chainId,c.contract,p.id,recipient,expires);const signature=await wallet().signMessage({account,message});const result=await api<{wrappedKey:Envelope['wrappedKey']}>('/api/lit',{operation:'decrypt',listingId:p.id,recipient,expires,signature,envelope:raw});return decryptCard(envelope,await open(pair.privateKey,result.wrappedKey,message));}
export async function listCard(c:AppConfig,account:Address,input:{brand:string;category:string;region:string;face:string;price:string;code:string;pin:string},progress:(s:string)=>void){await network();if(!await publicClient(c).readContract({address:c.contract as Address,abi:CardLaneAbi,functionName:'allowedSeller',args:[account]}))throw new Error('当前钱包尚未获得卖家资格');const id=('0x'+hex(fresh(32))) as Hex;const challenge=hex(fresh(32));progress('正在核验加密服务');const binding=await api<{publicKey:string;signature:Hex;challenge:string}>('/api/lit',{operation:'publicKey',challenge});const message=['CardLane key binding v1',String(c.chainId),c.contract.toLowerCase(),challenge,binding.publicKey].join('\n');if(binding.challenge!==challenge||!/^[0-9a-f]{64}$/.test(binding.publicKey)||!await verifyMessage({address:c.litIdentity as Address,message,signature:binding.signature}))throw new Error('加密公钥验证失败');progress('正在本地加密');const envelope=await encryptCard(id,{brand:input.brand,category:input.category,region:input.region,face:input.face},{code:input.code,pin:input.pin},unhex(binding.publicKey));const payload=JSON.stringify(envelope);const payloadHash=keccak256(toHex(payload));const expires=Math.floor(Date.now()/1000)+180;const signature=await wallet().signMessage({account,message:['CardLane upload v1',payloadHash,String(expires)].join('\n')});progress('正在上传加密文件');const {cid}=await api<{cid:string}>('/api/storage',{payload,seller:account,expires,signature});progress('正在上架');const hash=await wallet().writeContract({account,address:c.contract as Address,abi:CardLaneAbi,functionName:'createListing',args:[id,cid,payloadHash,parseUnits(input.price,6)]});if((await publicClient(c).waitForTransactionReceipt({hash})).status!=='success')throw new Error('上架交易失败');return hash;}

export async function resolveDispute(c:AppConfig,account:Address,id:Hex,refundBuyer:boolean){await network();const hash=await wallet().writeContract({account,address:c.contract as Address,abi:CardLaneAbi,functionName:'resolve',args:[id,refundBuyer]});if((await publicClient(c).waitForTransactionReceipt({hash})).status!=='success')throw new Error('争议处理交易失败');return hash;}

export async function openAppeal(c:AppConfig,account:Address,id:Hex,reason:number){await network();const hash=await wallet().writeContract({account,address:c.contract as Address,abi:CardLaneAbi,functionName:'dispute',args:[id,reason]});if((await publicClient(c).waitForTransactionReceipt({hash})).status!=='success')throw new Error('申诉提交失败');return hash;}
export async function replyToAppeal(c:AppConfig,account:Address,id:Hex,reply:string){await network();const hash=await wallet().writeContract({account,address:c.contract as Address,abi:CardLaneAbi,functionName:'replyToAppeal',args:[id,reply]});if((await publicClient(c).waitForTransactionReceipt({hash})).status!=='success')throw new Error('回复提交失败');return hash;}
